#!/usr/bin/env bash

set -e
set -o pipefail

export NULLSHA worktree
NULLSHA='0000000000000000000000000000000000000000'

function make-worktree() {
  worktree=$(mktemp -d -t pre-receive.XXX)
}

function ci() {
  local sha; sha=${1:-HEAD}
  echo "building $sha in $worktree"
  git --work-tree "$worktree" checkout $sha -- .
  pushd "$worktree"
  ./gradlew --no-daemon check
  popd
}

function main() {
  if [ -z "$GIT_DIR" ]; then
    echo 'error: script meant to be run as a git hook.' >&2
    exit 1
  fi

  while read oldsha newsha ref; do
    case $oldsha,$newsha in
      $NULLSHA,*)
        echo "create $ref as $newsha"
        ci $newsha
        ;;
      *,$NULLSHA)
        echo "delete $ref"
        ;;
      *,*)
        echo "update $ref from $oldsha to $newsha"
        ci $newsha
        ;;
    esac
  done
}

function cleanup() {
  rm -rf "$worktree"
}

make-worktree
trap cleanup EXIT
main |& tee -a $GIT_DIR/hooks/pre-receive.log
